name: storage_module
description: A Flutter package for storage implementation.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_interface:
    path: ../core_interface
  get_it: ^7.6.7
  injectable: ^2.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
